repos:
- repo: https://github.com/pierre-ernst/snyk-test-data 
  rev: maven 
  hooks:
    - id: snyk
      types: [file]
      files: ^(pom\.xml|build\.gradle|build\.gradle\.kts|requirements\.txt)$
      args: []
