name: Run Snyk test

on: 
  workflow_dispatch:

jobs:
  snyk:
    runs-on: ubuntu-latest
    name: A job to push semgrep baseline findings to GitHub
    steps:
      - uses: actions/checkout@v2
      - uses: snyk/actions/setup@master
      - name: Snyk Test
        run: snyk test 
        env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}    
