name: Run Snyk test

on: 
  workflow_dispatch:

jobs:
  snyk:
    runs-on: ubuntu-latest
    name: A job to push snyk findings to GitHub
    steps:
      - uses: actions/checkout@v2
      - uses: snyk/actions/setup@master
      - name: Snyk Test
        run: snyk test --sarif-file-output=snyk-sarif.json
        continue-on-error: true       
        env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}    
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk-sarif.json
